### ISSUE TITLE
Bump CasADi version to 3.5

### ISSUE THREAD

**Issue by jdeschut** [awebox/awebox#31]
- serialization of CasADi functions can be tremendously useful in many applications
- function timings available
- efficient implementation of `map`

https://web.casadi.org/get/

**Comment by thilobro** [comment]
Do you know whether all casadi objects can now be serialized (e.g. with pickle)?

**Comment by jdeschut** [comment]
What I am sure of:
- SX/MX Functions
- `nlpsol` instances
- `interpolant`
- `integrator`

There's even a wrapper for pickling:

```
f.save('f.casadi')            % Dump any CasADi Function to a file
f = Function.load('f.casadi') % Loads back in
```

**Comment by thilobro** [comment]
Seems like it's worth a try. We can run the tests with the new casadi version and see if anything breaks
