### ISSUE TITLE
make all "slack" treatment consistent

### ISSUE THREAD

**Issue by rcleuthold** [awebox/awebox#37]
there are (at present) at least two ways that slack variables seem to be represented:
- by variable names containing the string "slack" 
- by variables of type "us"

this is horrifyingly messy.

**Comment by jdeschut** [comment]
Hi! The different slack variable names represent different slack reformulations.

- `us`: inequalities `h` are reformulated as slacked equalities `h - us = 0`, with additional `us >=0` inequalities. The reformulated OCP is completely equivalent to the original one. This is a deprecated feature however (precursor feature of what is now implemented in the `tunempc` toolbox) and I will remove it at some point. In the mean time, the slack variables should not appear in the OCP unless explicitly activated by the user.

- `slack`: used for the standard soft constraint reformulation when generating an `awebox` MPC controller. So this one should stay. We can rename it to e.g. `s` though.

**Comment by jdeschut** [comment]
Resolved in #45
