### ISSUE TITLE
Restore non-lifted aero forces implementation

### ISSUE THREAD

**Issue by jdeschut** [awebox/awebox#47]

**Comment by rcleuthold** [comment]
yes. sorry. i'm doing this - should be done by tomorrow afternoon.

**Comment by jdeschut** [comment]
Hi @rcleuthold! Any update? This would be quite useful for me right now.

**Comment by rcleuthold** [comment]
Hi Joshi,
Yes, - sorry. It's done, but I broke something during my SOSC tuning. I'm
undoing the broken part, and then I'll push.

**Comment by jdeschut** [comment]
Maybe you could already open the Pull Request as WIP, then I could cherry-pick the necessary commits from there for the moment?

**Comment by rcleuthold** [comment]
Hi Joshi, it's already up.
https://github.com/awebox/awebox/pull/51
Hugs.

**Comment by jdeschut** [comment]
Thanks!
