### ISSUE TITLE
Correct tether kinetic energy term in lagrangian formalism

### ISSUE THREAD

**Issue by jdeschut** [awebox/awebox#54]
In the current implementation, a single tether element kinetic energy term is given by:

```
T_n = 1/2 * m_t/2 * (||dot(q)_n||^2 + ||dot(q)_{n-1}||^2)
```

whereas it should be
```
T_n = 1/2 * m_t/3 * (||dot(q)_n||^2 + ||dot(q)_{n-1}||^2 + dot(q)_n.T*dot(q)_{n-1})
```

(see, e.g., [Houska2007a](https://cdn.syscop.de/publications/Houska2007a.pdf), eq. 1.56).

The current error is particularly large when `dot(q)_n` and `dot(q)_{n+1}` differ greatly (up to factor 3/2 overestimation), but zero when `dot(q)_n = dot(q)_{n-1}`

The potential energy is implemented correctly.

**Comment by rcleuthold** [comment]
Hi Joshi (@jdeschut ), 
I think this *is* correct, though maybe I'm missing something? 

the kinetic energy of a top node is: 1/2 m_{top node} ||dq_{top node}||^2
and the kinetic energy of a bottom node is: 1/2 m_{bottom node} ||dq_{bottom node}||^2
so, the total kinetic energy must be the sum of these. 
.... provided that the tether mass is correctly allocated between the top and bottom node. and (?) i think (?) we do that correctly? 

if i've read the Houska equation correctly, this last term - the projection that doesn't seem to show up in the awebox - is exactly what we're doing with the "top mass allocation fraction," in lagr_dyn_dir.mass.py

i've attached a more complete explanation (of what i think is/should-be going on, below.) maybe look at page 4, and tell me what you think?

[standalone.pdf](https://github.com/awebox/awebox/files/5824013/standalone.pdf)

**Comment by rcleuthold** [comment]
i was thinking about our call, and i think you're right that we should fix
this (nowish).
want to go ahead?

**Comment by jdeschut** [comment]
cool, yes I'll have a pull request up by the end of the week latest.
