### ISSUE TITLE
Correct drag power formula?

### ISSUE THREAD

**Issue by jdeschut** [awebox/awebox#57]
Current formula (A) is
```python
kite_drag_power = -1. * cas.mtimes(
        variables_si['xd']['dq{}{}'.format(kite, parent)].T,
        outputs['aerodynamics']['f_gen{}'.format(kite)]
)
```
whereas in other papers, e.g. Zanon2013, or Malz2020 or Makani technical report, it is (B):
```
kite_drag_power = -1. * cas.mtimes(
        outputs['aerodynamics']['air_velocity{}'.format(kite)].T,
        outputs['aerodynamics']['f_gen{}'.format(kite)]
)
```
At high kite speeds the two are almost identical, but nevertheless we should opt for the most physically consistent option.

Option (A), discussed also with Dr. Christoph Sieg, is consistent from the mechanics viewpoint that in order to get the extracted propeller power, we multiply the thrust force exerted by the rotor disk, with the speed of said disk.

Option (B) is more consistent from an actuator-disk point of view on thrust power. An efficiency factor can then be introduced to represent how much thrust power can be transformed into actual propeller motion (and generator efficiency).

I tend to prefer option (B), to stay aligned with the existing consensus in the literature.

**Comment by rcleuthold** [comment]
The difficulty in Option (B), is that the propeller's should also be
influencing the air_velocity. But they're not currently... So, honestly,
both options are "incorrect", and we should choose the one that we like
best for *whatever* reason in the meantime (ie, simplicity for A, and
clarity for B). I'm ok with either.

**Comment by jdeschut** [comment]
Though I did not find an explicit reasoning, I was under the impression in the Makani files that they "modeled" the (assumed to be constant) induction effect approximately with this efficiency factor, which also includes e.g. projection losses, ... It's a bit crude but good enough at the moment I guess.

**Comment by rcleuthold** [comment]
i agree, and am (90% sure that) Thomas Haas would also agree.
