### ISSUE TITLE
Bug in "multi" tether drag model?

### ISSUE THREAD

**Issue by jdeschut** [awebox/awebox#66]
In `frames.get_inverse_equivalence_matrix()`, assuming the ordering ```[Fx, Fy, Fz, Mx, My, 0].T```

```
    Ainv_row1 = cas.horzcat(half, 0., 0., over, 0., 0.)
    Ainv_row2 = cas.horzcat(0., half, 0., 0., over., 0.)
```
should be
```
    Ainv_row1 = cas.horzcat(half, 0., 0., 0., over, 0.)
    Ainv_row2 = cas.horzcat(0., half, 0., over, 0., 0.)
```

Similarly,
```
    Ainv_row4 = cas.horzcat(half, 0., 0., nver, 0., 0.)
    Ainv_row5 = cas.horzcat(0., half, 0., 0., nver, 0.)
```
should be
```
    Ainv_row4 = cas.horzcat(half, 0., 0., 0., nver, 0.)
    Ainv_row5 = cas.horzcat(0., half, 0., nver, 0., 0.)
```

Could you double check @rcleuthold ? Maybe I'm not using the correct ordering?

There is also a typo in the comments I think:
```
    # L (a - d) = My
    # L (a - e) = Mx
 ```
should be 
```
    # L (a - d) / 2 = My
    # L (b - e) / 2 = Mx
 ```
 (probably a typo as the implementation is correct)

**Comment by rcleuthold** [comment]
Hi Joshi,
I think the matrices *are* correct --- maybe I've made a mistake in my
derivation? (See attached pdf).

But, the comments thing is a typo, I think, left over from a previous
definition of L.

All the best, Rachel
